// Start North

export const chitipaCodes = [
  { code: "101100", name: "Chitipa BOMA", group: "chitipa" },
  { code: "101101", name: "TA Kameme", group: "chitipa" },
  { code: "101102", name: "BSTA Bulambya Songwe", group: "chitipa" },
  { code: "101103", name: "TA Mwabulambya", group: "chitipa" },
  { code: "101104", name: "TA Mwenemisuku", group: "chitipa" },
  { code: "101105", name: "STA Lwangwa", group: "chitipa" },
  { code: "101106", name: "TA Mwenewenya", group: "chitipa" },
  { code: "101107", name: "STA Nthengatenga", group: "chitipa" },
  { code: "101108", name: "TA Nthalire", group: "chitipa" },
  { code: "101109", name: "STA Wavikaza", group: "chitipa" },
];
export const karongaCodes = [
  { code: "102100", name: "Karonga", group: "karonga" },
  { code: "102101", name: "Songwe", group: "karonga" },
  { code: "102102", name: "Mwakaboko", group: "karonga" },
  { code: "102103", name: "Kilupula", group: "karonga" },
  { code: "102104", name: "Kyungu", group: "karonga" },
  { code: "102105", name: "Mwirang?ombe", group: "karonga" },
  { code: "102106", name: "Wasambo", group: "karonga" },
];
export const likomaCodes = [
  { code: "107100", name: "Likoma BOMA", group: "likoma" },
  { code: "107101", name: "Mkumpha", group: "likoma" },
];
export const mzimbaCodes = [
  { code: "104100", name: "Mzimba BOMA", group: "mzimba" },
  { code: "104101", name: "Jaravikuba Munthali", group: "mzimba" },
  { code: "104102", name: "Mtwalo", group: "mzimba" },
  { code: "104103", name: "Ekwendeni Township", group: "mzimba" },
  { code: "104104", name: "Mpherembe", group: "mzimba" },
  { code: "104105", name: "Chindi", group: "mzimba" },
  { code: "104106", name: "Kampingo Sibande", group: "mzimba" },
  { code: "104107", name: "M?mbelwa", group: "mzimba" },
  { code: "104108", name: "Mzukuzuku", group: "mzimba" },
  { code: "104109", name: "Mzikubola", group: "mzimba" },
  { code: "104110", name: "Levi Jere", group: "mzimba" },
  { code: "104111", name: "Jenda Township", group: "mzimba" },
  { code: "104112", name: "Mabulabo", group: "mzimba" },
  { code: "104113", name: "Khosolo Gwaza Jere", group: "mzimba" },
  { code: "104114", name: "Vwaza Marsh Reserve", group: "mzimba" },
];
export const mzuzuCodes = [
  { code: "105200", name: "Mzuzu CBD", group: "mzuzu" },
  { code: "105201", name: "Khorongo", group: "mzuzu" },
  { code: "105202", name: "Lupaso", group: "mzuzu" },
  { code: "105203", name: "Luwinga", group: "mzuzu" },
  { code: "105204", name: "Mchengautuwa", group: "mzuzu" },
  { code: "105205", name: "Chibanja", group: "mzuzu" },
  { code: "105206", name: "Katoto", group: "mzuzu" },
  { code: "105207", name: "Zolozolo", group: "mzuzu" },
  { code: "105208", name: "Hilltop", group: "mzuzu" },
  { code: "105209", name: "Chiputula", group: "mzuzu" },
  { code: "105210", name: "Mzilawaingwe", group: "mzuzu" },
  { code: "105211", name: "Katawa", group: "mzuzu" },
  { code: "105212", name: "Chasefu", group: "mzuzu" },
  { code: "105213", name: "Lunyangwa", group: "mzuzu" },
  { code: "105214", name: "Kaningina", group: "mzuzu" },
  { code: "105215", name: "Masasa", group: "mzuzu" },
  { code: "105216", name: "Msongwe", group: "mzuzu" },
];
export const nkhata_bayCodes = [
  { code: "106100", name: "Nkhata Bay BOMA", group: "nkhata_bay" },
  { code: "106101", name: "Mkondowe", group: "nkhata_bay" },
  { code: "106102", name: "Boghoyo", group: "nkhata_bay" },
  { code: "106103", name: "M?bwana", group: "nkhata_bay" },
  { code: "106104", name: "Nyaluwanga", group: "nkhata_bay" },
  { code: "106105", name: "Timbiri", group: "nkhata_bay" },
  { code: "106106", name: "Mkumbira", group: "nkhata_bay" },
  { code: "106107", name: "Mankhambira", group: "nkhata_bay" },
  { code: "106108", name: "Fukamalaza", group: "nkhata_bay" },
  { code: "106109", name: "Malanda", group: "nkhata_bay" },
  { code: "106110", name: "Kabunduli", group: "nkhata_bay" },
  { code: "106111", name: "Malenga Mzoma", group: "nkhata_bay" },
  { code: "106112", name: "Fukamapiri", group: "nkhata_bay" },
  { code: "106113", name: "Zilakoma", group: "nkhata_bay" },
];
export const rumphiCodes = [
  { code: "103100", name: "Rumphi BOMA", group: "rumphi" },
  { code: "103101", name: "Mwalweni", group: "rumphi" },
  { code: "103102", name: "Kachulu", group: "rumphi" },
  { code: "103103", name: "Njikula", group: "rumphi" },
  { code: "103104", name: "Mwamlowe", group: "rumphi" },
  { code: "103105", name: "Chapinduka", group: "rumphi" },
  { code: "103106", name: "Mwankhunikira", group: "rumphi" },
  { code: "103107", name: "Mwahenga", group: "rumphi" },
  { code: "103108", name: "Chisovya", group: "rumphi" },
  { code: "103109", name: "Chikulamayembe", group: "rumphi" },
  { code: "103110", name: "Katumbi", group: "rumphi" },
  { code: "103111", name: "Zolekere", group: "rumphi" },
  { code: "103112", name: "Nyika National Park", group: "rumphi" },
];

//End North

// Start Central

export const dedzaCodes = [
  { code: "209100", name: "Dedza Township", group: "dedza" },
  { code: "209101", name: "Tambala", group: "dedza" },
  { code: "209102", name: "Chauma", group: "dedza" },
  { code: "209103", name: "Kasumbu", group: "dedza" },
  { code: "209104", name: "Kachindamoto", group: "dedza" },
  { code: "209105", name: "Kamenya Gwaza", group: "dedza" },
  { code: "209106", name: "Kaphuka", group: "dedza" },
  { code: "209107", name: "Chilikumwendo", group: "dedza" },
  { code: "209108", name: "Kachere", group: "dedza" },
];
export const dowaCodes = [
  { code: "204100", name: "Dowa BOMA", group: "dowa" },
  { code: "204101", name: "Chakhaza", group: "dowa" },
  { code: "204102", name: "Dzoole", group: "dowa" },
  { code: "204103", name: "Kayembe", group: "dowa" },
  { code: "204104", name: "Mponela", group: "dowa" },
  { code: "204105", name: "Mponela Township", group: "dowa" },
  { code: "204106", name: "Msakambewa", group: "dowa" },
  { code: "204107", name: "Mkukula", group: "dowa" },
  { code: "204108", name: "Lumbadzi Township", group: "dowa" },
  { code: "204109", name: "Chiwere", group: "dowa" },
];
export const kasungu_municipalityCodes = [
  {
    code: "201300",
    name: "Kasungu Central Township",
    group: "kasungu_municipality",
  },
  { code: "201301", name: "Chipala", group: "kasungu_municipality" },
  { code: "201302", name: "Mponda", group: "kasungu_municipality" },
  { code: "201303", name: "Bunda", group: "kasungu_municipality" },
  { code: "201304", name: "Belele", group: "kasungu_municipality" },
  { code: "201305", name: "Chankhanga", group: "kasungu_municipality" },
  { code: "201306", name: "Kasalika", group: "kasungu_municipality" },
  { code: "201307", name: "Kapalankhwazi", group: "kasungu_municipality" },
  { code: "201308", name: "Chitete", group: "kasungu_municipality" },
  { code: "201309", name: "Kamvunguti", group: "kasungu_municipality" },
  { code: "201310", name: "Chimbuna", group: "kasungu_municipality" },
  { code: "201311", name: "Gundani", group: "kasungu_municipality" },
];
export const kasungu_ruralCodes = [
  { code: "201100", name: "Chisikwa", group: "kasungu_rural" },
  { code: "201101", name: "Kaluluma", group: "kasungu_rural" },
  { code: "201102", name: "Chisinga", group: "kasungu_rural" },
  { code: "201103", name: "Chisemphere", group: "kasungu_rural" },
  { code: "201104", name: "Chulu", group: "kasungu_rural" },
  { code: "201105", name: "M?nyanja", group: "kasungu_rural" },
  { code: "201106", name: "Simlemba", group: "kasungu_rural" },
  { code: "201107", name: "Mphomwa", group: "kasungu_rural" },
  { code: "201108", name: "Kaphaizi", group: "kasungu_rural" },
  { code: "201109", name: "Mwase", group: "kasungu_rural" },
  { code: "201110", name: "Kaomba", group: "kasungu_rural" },
  { code: "201111", name: "Wimbe", group: "kasungu_rural" },
  { code: "201112", name: "Kapelula", group: "kasungu_rural" },
  { code: "201113", name: "Kapichira", group: "kasungu_rural" },
  { code: "201114", name: "Mdunga", group: "kasungu_rural" },
  { code: "201115", name: "Chilowamatambe", group: "kasungu_rural" },
  { code: "201116", name: "Chambwe", group: "kasungu_rural" },
  { code: "201117", name: "Mangwazu", group: "kasungu_rural" },
  { code: "201118", name: "Mawawa", group: "kasungu_rural" },
  { code: "201119", name: "Lukwa", group: "kasungu_rural" },
  { code: "201120", name: "Njombwa", group: "kasungu_rural" },
  { code: "201121", name: "Kawamba", group: "kasungu_rural" },
  { code: "201122", name: "Nthunduwala", group: "kasungu_rural" },
  { code: "201123", name: "Chaima", group: "kasungu_rural" },
  { code: "201124", name: "Chidzuma", group: "kasungu_rural" },
  { code: "201125", name: "Santhe", group: "kasungu_rural" },
  { code: "201126", name: "Kasungu National Park", group: "kasungu_rural" },
];
export const lilongwe_ruralCodes = [
  { code: "206101", name: "Khongoni", group: "lilongwe_rural" },
  { code: "206102", name: "Kabudula", group: "lilongwe_rural" },
  { code: "206103", name: "Mtema", group: "lilongwe_rural" },
  { code: "206104", name: "Mbang?ombe", group: "lilongwe_rural" },
  { code: "206105", name: "Chitukula", group: "lilongwe_rural" },
  { code: "206106", name: "Chimutu", group: "lilongwe_rural" },
  { code: "206107", name: "Chitekwele", group: "lilongwe_rural" },
  { code: "206108", name: "Mazengera", group: "lilongwe_rural" },
  { code: "206109", name: "Kalumbu", group: "lilongwe_rural" },
  { code: "206110", name: "Chadza", group: "lilongwe_rural" },
  { code: "206111", name: "Kalumba", group: "lilongwe_rural" },
  { code: "206112", name: "Tsabango", group: "lilongwe_rural" },
  { code: "206113", name: "Njewa", group: "lilongwe_rural" },
  { code: "206114", name: "Malili", group: "lilongwe_rural" },
  { code: "206115", name: "Kalolo", group: "lilongwe_rural" },
  { code: "206116", name: "Masumbankhunda", group: "lilongwe_rural" },
  { code: "206117", name: "Chiseka", group: "lilongwe_rural" },
  { code: "206118", name: "Masula", group: "lilongwe_rural" },
];
export const lilongwe_urbanCodes = [
  { code: "207201", name: "Area 1", group: "lilongwe_urban" },
  { code: "207202", name: "Area 2", group: "lilongwe_urban" },
  { code: "207203", name: "Area 3", group: "lilongwe_urban" },
  { code: "207204", name: "Area 4", group: "lilongwe_urban" },
  { code: "207205", name: "Area 5", group: "lilongwe_urban" },
  { code: "207206", name: "Area 6", group: "lilongwe_urban" },
  { code: "207207", name: "Area 7", group: "lilongwe_urban" },
  { code: "207208", name: "Area 8", group: "lilongwe_urban" },
  { code: "207209", name: "Area 9", group: "lilongwe_urban" },
  { code: "207210", name: "Area 10", group: "lilongwe_urban" },
  { code: "207211", name: "Area 11", group: "lilongwe_urban" },
  { code: "207212", name: "Area 12", group: "lilongwe_urban" },
  { code: "207213", name: "Area 13", group: "lilongwe_urban" },
  { code: "207214", name: "Area 14", group: "lilongwe_urban" },
  { code: "207215", name: "Area 15", group: "lilongwe_urban" },
  { code: "207216", name: "Area 16", group: "lilongwe_urban" },
  { code: "207217", name: "Area 17", group: "lilongwe_urban" },
  { code: "207218", name: "Area 18", group: "lilongwe_urban" },
  { code: "207219", name: "Area 19", group: "lilongwe_urban" },
  { code: "207220", name: "Area 20", group: "lilongwe_urban" },
  { code: "207221", name: "Area 21", group: "lilongwe_urban" },
  { code: "207222", name: "Area 22", group: "lilongwe_urban" },
  { code: "207223", name: "Area 23", group: "lilongwe_urban" },
  { code: "207224", name: "Area 24", group: "lilongwe_urban" },
  { code: "207225", name: "Area 25", group: "lilongwe_urban" },
  { code: "207226", name: "Area 26", group: "lilongwe_urban" },
  { code: "207227", name: "Area 27", group: "lilongwe_urban" },
  { code: "207228", name: "Area 28", group: "lilongwe_urban" },
  { code: "207229", name: "Area 29", group: "lilongwe_urban" },
  { code: "207230", name: "Area 30", group: "lilongwe_urban" },
  { code: "207231", name: "Area 31", group: "lilongwe_urban" },
  { code: "207232", name: "Area 32", group: "lilongwe_urban" },
  { code: "207233", name: "Area 33", group: "lilongwe_urban" },
  { code: "207234", name: "Area 34", group: "lilongwe_urban" },
  { code: "207235", name: "Area 35", group: "lilongwe_urban" },
  { code: "207236", name: "Area 36", group: "lilongwe_urban" },
  { code: "207237", name: "Area 37", group: "lilongwe_urban" },
  { code: "207238", name: "Area 38", group: "lilongwe_urban" },
  { code: "207239", name: "Area 39", group: "lilongwe_urban" },
  { code: "207240", name: "Area 40", group: "lilongwe_urban" },
  { code: "207241", name: "Area 41", group: "lilongwe_urban" },
  { code: "207242", name: "Area 42", group: "lilongwe_urban" },
  { code: "207243", name: "Area 43", group: "lilongwe_urban" },
  { code: "207244", name: "Area 44", group: "lilongwe_urban" },
  { code: "207245", name: "Area 45", group: "lilongwe_urban" },
  { code: "207246", name: "Area 46", group: "lilongwe_urban" },
  { code: "207247", name: "Area 47", group: "lilongwe_urban" },
  { code: "207248", name: "Area 48", group: "lilongwe_urban" },
  { code: "207249", name: "Area 49", group: "lilongwe_urban" },
  { code: "207250", name: "Area 50", group: "lilongwe_urban" },
  { code: "207251", name: "Area 51", group: "lilongwe_urban" },
  { code: "207252", name: "Area 52", group: "lilongwe_urban" },
  { code: "207253", name: "Area 53", group: "lilongwe_urban" },
  { code: "207254", name: "Area 54", group: "lilongwe_urban" },
  { code: "207255", name: "Area 55", group: "lilongwe_urban" },
  { code: "207256", name: "Area 56", group: "lilongwe_urban" },
  { code: "207257", name: "Area 57", group: "lilongwe_urban" },
  { code: "207258", name: "Area 58", group: "lilongwe_urban" },
];
export const mchinjiCodes = [
  { code: "205100", name: "Mchinji BOMA", group: "mchinji" },
  { code: "205101", name: "Gumba", group: "mchinji" },
  { code: "205102", name: "Mkanda", group: "mchinji" },
  { code: "205103", name: "Dambe", group: "mchinji" },
  { code: "205104", name: "Pitala", group: "mchinji" },
  { code: "205105", name: "Kazyozyo", group: "mchinji" },
  { code: "205106", name: "Kapunula", group: "mchinji" },
  { code: "205107", name: "Kapondo", group: "mchinji" },
  { code: "205108", name: "Mduwa", group: "mchinji" },
  { code: "205109", name: "Nyoka", group: "mchinji" },
  { code: "205110", name: "Mlonyeni", group: "mchinji" },
  { code: "205111", name: "Zulu", group: "mchinji" },
  { code: "205112", name: "Simphasi", group: "mchinji" },
  { code: "205113", name: "Mavwere", group: "mchinji" },
];
export const nkhota_kotaCodes = [
  { code: "202100", name: "Nkhotakota BOMA", group: "nkhota_kota" },
  { code: "202101", name: "Kafuzila", group: "nkhota_kota" },
  { code: "202102", name: "Kanyenda", group: "nkhota_kota" },
  { code: "202103", name: "Dwangwa Township", group: "nkhota_kota" },
  { code: "202104", name: "Mphonde", group: "nkhota_kota" },
  { code: "202105", name: "Malenga Chanzi", group: "nkhota_kota" },
  { code: "202106", name: "Kalimanjira", group: "nkhota_kota" },
  { code: "202107", name: "Mwadzama", group: "nkhota_kota" },
  { code: "202108", name: "Mwansambo", group: "nkhota_kota" },
  { code: "202109", name: "Nkhotakota Game Reserve", group: "nkhota_kota" },
];
export const ntcheuCodes = [
  { code: "210100", name: "Ntcheu BOMA", group: "ntcheu" },
  { code: "210101", name: "Masasa", group: "ntcheu" },
  { code: "210102", name: "Chakhumbira", group: "ntcheu" },
  { code: "210103", name: "Goodson Ganya", group: "ntcheu" },
  { code: "210104", name: "Njolomole", group: "ntcheu" },
  { code: "210105", name: "Kwataine", group: "ntcheu" },
  { code: "210106", name: "Makwangwala", group: "ntcheu" },
  { code: "210107", name: "Mkutumula", group: "ntcheu" },
  { code: "210108", name: "Champiti", group: "ntcheu" },
  { code: "210109", name: "Mpando", group: "ntcheu" },
  { code: "210110", name: "Phambala", group: "ntcheu" },
  { code: "210111", name: "Tsikulamowa", group: "ntcheu" },
];
export const ntchisiCodes = [
  { code: "203100", name: "Ntchisi BOMA", group: "ntchisi" },
  { code: "203101", name: "Chilooko", group: "ntchisi" },
  { code: "203102", name: "Nthondo", group: "ntchisi" },
  { code: "203103", name: "Malenga", group: "ntchisi" },
  { code: "203104", name: "Kasakula", group: "ntchisi" },
  { code: "203105", name: "Kalumo", group: "ntchisi" },
  { code: "203106", name: "Vuso Jere", group: "ntchisi" },
  { code: "203107", name: "Chikho", group: "ntchisi" },
];
export const salimaCodes = [
  { code: "208100", name: "Salima Township", group: "salima" },
  { code: "208101", name: "Msosa", group: "salima" },
  { code: "208102", name: "Khombedza", group: "salima" },
  { code: "208103", name: "Mwanza", group: "salima" },
  { code: "208104", name: "Kuluunda", group: "salima" },
  { code: "208105", name: "Karonga", group: "salima" },
  { code: "208106", name: "Maganga", group: "salima" },
  { code: "208107", name: "Kambwiri", group: "salima" },
  { code: "208108", name: "Pemba", group: "salima" },
  { code: "208109", name: "Ndindi", group: "salima" },
  { code: "208110", name: "Chipoka Township", group: "salima" },
  { code: "208111", name: "Kambalame", group: "salima" },
];

// end Central

export const balakaCodes = [
  { code: "302100", name: "Balaka", group: "balaka" },
  { code: "302101", name: "Kachenga", group: "balaka" },
  { code: "302102", name: "Kalembo", group: "balaka" },
  { code: "302103", name: "Amidu", group: "balaka" },
  { code: "302104", name: "Toleza", group: "balaka" },
  { code: "302105", name: "Matola", group: "balaka" },
  { code: "302106", name: "Sawali", group: "balaka" },
  { code: "302107", name: "Msamala", group: "balaka" },
  { code: "302108", name: "Chanthunya", group: "balaka" },
  { code: "302109", name: "Phalula", group: "balaka" },
  { code: "302110", name: "Nkaya", group: "balaka" },
];
export const blantyre_ruralCodes = [
  { code: "311101", name: "Chigaru", group: "blantyre_rural" },
  { code: "311102", name: "Lundu", group: "blantyre_rural" },
  { code: "311103", name: "Kunthembwe", group: "blantyre_rural" },
  { code: "311104", name: "Kuntaja", group: "blantyre_rural" },
  { code: "311105", name: "Chileka", group: "blantyre_rural" },
  { code: "311106", name: "Kapeni", group: "blantyre_rural" },
  { code: "311107", name: "Lunzu Township", group: "blantyre_rural" },
  { code: "311108", name: "Makata", group: "blantyre_rural" },
  { code: "311109", name: "Machinjiri", group: "blantyre_rural" },
  { code: "311110", name: "Somba", group: "blantyre_rural" },
  { code: "311111", name: "Mpemba", group: "blantyre_rural" },
];
export const blantyre_urbanCodes = [
  { code: "312200", name: "Blantyre CBD", group: "blantyre_urban" },
  { code: "312201", name: "Mapanga", group: "blantyre_urban" },
  { code: "312202", name: "Kachere", group: "blantyre_urban" },
  { code: "312203", name: "Maone", group: "blantyre_urban" },
  { code: "312204", name: "Nkolokoti", group: "blantyre_urban" },
  { code: "312205", name: "Ndirande", group: "blantyre_urban" },
  { code: "312206", name: "South Lunzu", group: "blantyre_urban" },
  { code: "312207", name: "Kameza", group: "blantyre_urban" },
  { code: "312208", name: "Chirimba", group: "blantyre_urban" },
  { code: "312209", name: "Chemusa", group: "blantyre_urban" },
  { code: "312210", name: "Mbayani", group: "blantyre_urban" },
  { code: "312211", name: "Nyambadwe", group: "blantyre_urban" },
  { code: "312212", name: "Chilomoni", group: "blantyre_urban" },
  { code: "312213", name: "Namiwawa", group: "blantyre_urban" },
  { code: "312214", name: "Sunnyside", group: "blantyre_urban" },
  { code: "312215", name: "Nancholi", group: "blantyre_urban" },
  { code: "312216", name: "Zingwangwa", group: "blantyre_urban" },
  { code: "312217", name: "Chilobwe", group: "blantyre_urban" },
  { code: "312218", name: "Chimwankhunda", group: "blantyre_urban" },
  { code: "312219", name: "Manja", group: "blantyre_urban" },
  { code: "312220", name: "Nkolokosa", group: "blantyre_urban" },
  { code: "312221", name: "Chitawira", group: "blantyre_urban" },
  { code: "312222", name: "Naperi", group: "blantyre_urban" },
  { code: "312223", name: "Mount Pleasant", group: "blantyre_urban" },
  { code: "312224", name: "Mandala", group: "blantyre_urban" },
  { code: "312225", name: "Chichiri", group: "blantyre_urban" },
  { code: "312226", name: "Chinyonga", group: "blantyre_urban" },
  { code: "312227", name: "Kanjedza", group: "blantyre_urban" },
  { code: "312228", name: "Mudi", group: "blantyre_urban" },
  { code: "312229", name: "Limbe", group: "blantyre_urban" },
  { code: "312230", name: "Mpingwe", group: "blantyre_urban" },
  { code: "312231", name: "Bangwe", group: "blantyre_urban" },
  { code: "312232", name: "Namiyango", group: "blantyre_urban" },
  { code: "312233", name: "BCA", group: "blantyre_urban" },
  { code: "312234", name: "Misesa", group: "blantyre_urban" },
  { code: "312235", name: "Chiwembe", group: "blantyre_urban" },
  { code: "312236", name: "Angelogothere", group: "blantyre_urban" },
  { code: "312237", name: "Che Somba", group: "blantyre_urban" },
  { code: "312238", name: "Chigumula", group: "blantyre_urban" },
];
export const chikwawaCodes = [
  { code: "315100", name: "Chikwawa BOMA", group: "chikwawa" },
  { code: "315101", name: "Chapananga", group: "chikwawa" },
  { code: "315102", name: "Kasisi", group: "chikwawa" },
  { code: "315103", name: "Mlilima", group: "chikwawa" },
  { code: "315104", name: "Katunga", group: "chikwawa" },
  { code: "315105", name: "Maseya", group: "chikwawa" },
  { code: "315106", name: "Ndakwela", group: "chikwawa" },
  { code: "315107", name: "Lundu", group: "chikwawa" },
  { code: "315108", name: "Nchalo Township", group: "chikwawa" },
  { code: "315109", name: "Makhwira", group: "chikwawa" },
  { code: "315110", name: "Ngabu", group: "chikwawa" },
  { code: "315111", name: "Ngabu Township", group: "chikwawa" },
  { code: "315112", name: "Ngowe", group: "chikwawa" },
  { code: "315113", name: "Masache", group: "chikwawa" },
  { code: "315114", name: "Lengwe National Park", group: "chikwawa" },
  { code: "315115", name: "Majete Game Reserve", group: "chikwawa" },
];
export const chiradzuluCodes = [
  { code: "306100", name: "Chiradzulu BOMA", group: "chiradzulu" },
  { code: "306101", name: "Chitera", group: "chiradzulu" },
  { code: "306102", name: "Mpama", group: "chiradzulu" },
  { code: "306103", name: "Nchema", group: "chiradzulu" },
  { code: "306104", name: "Sandaraki", group: "chiradzulu" },
  { code: "306105", name: "Kadewere", group: "chiradzulu" },
  { code: "306106", name: "Onga", group: "chiradzulu" },
  { code: "306107", name: "Likoswe", group: "chiradzulu" },
  { code: "306108", name: "Mpunga", group: "chiradzulu" },
  { code: "306109", name: "Nkalo", group: "chiradzulu" },
];
// TODO: Move this to district
export const luchenza_municipalityCodes = [
  { code: "309300", name: "Luchenza Township", group: "luchenza_municipality" },
];
export const machingaCodes = [
  { code: "303100", name: "Machinja BOMA", group: "machinga" },
  { code: "303101", name: "Liwonde Township", group: "machinga" },
  { code: "303102", name: "Nyambi", group: "machinga" },
  { code: "303103", name: "Chesale", group: "machinga" },
  { code: "303104", name: "Ngokwe", group: "machinga" },
  { code: "303105", name: "Chikweo", group: "machinga" },
  { code: "303106", name: "Nchinguza", group: "machinga" },
  { code: "303107", name: "Kapoloma", group: "machinga" },
  { code: "303108", name: "Nkoola", group: "machinga" },
  { code: "303109", name: "Chiwalo", group: "machinga" },
  { code: "303110", name: "Liwonde", group: "machinga" },
  { code: "303111", name: "Kawinga", group: "machinga" },
  { code: "303112", name: "Mlomba", group: "machinga" },
  { code: "303113", name: "Nsanama", group: "machinga" },
  { code: "303114", name: "Mposa", group: "machinga" },
  { code: "303115", name: "Chamba", group: "machinga" },
  { code: "303116", name: "Sitola", group: "machinga" },
  { code: "303117", name: "Mkula", group: "machinga" },
  { code: "303118", name: "Liwonde National Park", group: "machinga" },
];
export const mangochi_ruralCodes = [
  { code: "301100", name: "Lulanga", group: "mangochi_rural" },
  { code: "301101", name: "Makanjila", group: "mangochi_rural" },
  { code: "301102", name: "Namabvi", group: "mangochi_rural" },
  { code: "301103", name: "Katuli", group: "mangochi_rural" },
  { code: "301104", name: "Chowe", group: "mangochi_rural" },
  { code: "301105", name: "Jalasi", group: "mangochi_rural" },
  { code: "301106", name: "Mbwana Nyambi", group: "mangochi_rural" },
  { code: "301107", name: "Chiunda", group: "mangochi_rural" },
  { code: "301108", name: "Nankumba", group: "mangochi_rural" },
  { code: "301109", name: "Monkey Bay Township", group: "mangochi_rural" },
  { code: "301110", name: "Mponda", group: "mangochi_rural" },
  { code: "301111", name: "Ntonda", group: "mangochi_rural" },
  { code: "301112", name: "Chilipa", group: "mangochi_rural" },
  { code: "301113", name: "Chimwala", group: "mangochi_rural" },
  {
    code: "301114",
    name: "Lake Malawi National Park",
    group: "mangochi_rural",
  },
];
export const mangochi_townCodes = [
  { code: "301400", name: "Mangochi Central Township", group: "mangochi_town" },
  { code: "301401", name: "Koche", group: "mangochi_town" },
  { code: "301402", name: "Thundu", group: "mangochi_town" },
  { code: "301403", name: "Chigawe", group: "mangochi_town" },
  { code: "301404", name: "Mikomwa", group: "mangochi_town" },
  { code: "301405", name: "Nkanamwano", group: "mangochi_town" },
  { code: "301406", name: "Kalungu", group: "mangochi_town" },
  { code: "301407", name: "Msukamwere", group: "mangochi_town" },
  { code: "301408", name: "Mtumbwasi", group: "mangochi_town" },
  { code: "301409", name: "Mwasa", group: "mangochi_town" },
  { code: "301410", name: "Ndege", group: "mangochi_town" },
  { code: "301411", name: "Chikole", group: "mangochi_town" },
  { code: "301412", name: "Msikisi", group: "mangochi_town" },
];
export const mulanjeCodes = [
  { code: "308100", name: "Mulanje BOMA", group: "mulanje" },
  { code: "308101", name: "Juma", group: "mulanje" },
  { code: "308102", name: "Nkanda", group: "mulanje" },
  { code: "308103", name: "Nthiramanja", group: "mulanje" },
  { code: "308104", name: "Chikumbu", group: "mulanje" },
  { code: "308105", name: "Tombondiya", group: "mulanje" },
  { code: "308106", name: "Mabuka", group: "mulanje" },
  { code: "308107", name: "Sunganinzeru", group: "mulanje" },
  { code: "308108", name: "Laston Njema", group: "mulanje" },
  { code: "308109", name: "Mulanje Mountain Reserve", group: "mulanje" },
];
export const mwanzaCodes = [
  { code: "314100", name: "Mwanza BOMA", group: "mwanza" },
  { code: "314101", name: "Kanduku", group: "mwanza" },
  { code: "314102", name: "Nthache", group: "mwanza" },
  { code: "314103", name: "Govati", group: "mwanza" },
];
export const nenoCodes = [
  { code: "313100", name: "Neno BOMA", group: "neno" },
  { code: "313101", name: "Dambe", group: "neno" },
  { code: "313102", name: "Chekucheku", group: "neno" },
  { code: "313103", name: "Symon Likongwe", group: "neno" },
  { code: "313104", name: "Zalewa Township", group: "neno" },
  { code: "313105", name: "Mlauli", group: "neno" },
];
export const nsanjeCodes = [
  { code: "316100", name: "Nsanje BOMA", group: "nsanje" },
  { code: "316101", name: "Mlolo", group: "nsanje" },
  { code: "316102", name: "Mbenje", group: "nsanje" },
  { code: "316103", name: "Bangula Township", group: "nsanje" },
  { code: "316104", name: "Tengani", group: "nsanje" },
  { code: "316105", name: "Malemia", group: "nsanje" },
  { code: "316106", name: "Ngabu", group: "nsanje" },
  { code: "316107", name: "Makoko", group: "nsanje" },
  { code: "316108", name: "Chimombo", group: "nsanje" },
  { code: "316109", name: "Nyachikadza", group: "nsanje" },
  { code: "316110", name: "Ndamera", group: "nsanje" },
  { code: "316111", name: "Mwabvi Game Reserve", group: "nsanje" },
];
export const phalombeCodes = [
  { code: "307100", name: "Phalombe BOMA", group: "phalombe" },
  { code: "307101", name: "Migowi Township", group: "phalombe" },
  { code: "307102", name: "Chiwalo", group: "phalombe" },
  { code: "307103", name: "Jenala", group: "phalombe" },
  { code: "307104", name: "Mkhumba", group: "phalombe" },
  { code: "307105", name: "Kaduya", group: "phalombe" },
  { code: "307106", name: "Nazombe", group: "phalombe" },
  { code: "307107", name: "Nkhulambe", group: "phalombe" },
];
export const thyoloCodes = [
  { code: "310100", name: "Thyolo BOMA", group: "thyolo" },
  { code: "310101", name: "Bvumbwe", group: "thyolo" },
  { code: "310102", name: "Thomas", group: "thyolo" },
  { code: "310103", name: "Mphuka", group: "thyolo" },
  { code: "310104", name: "Boyidi", group: "thyolo" },
  { code: "310105", name: "Chimaliro", group: "thyolo" },
  { code: "310106", name: "Ngolongoliwa", group: "thyolo" },
  { code: "310107", name: "Nanseta", group: "thyolo" },
  { code: "310108", name: "Ndalama", group: "thyolo" },
  { code: "310109", name: "Nchilamwela", group: "thyolo" },
  { code: "310110", name: "Kapichi", group: "thyolo" },
  { code: "310111", name: "Kwethemule", group: "thyolo" },
  { code: "310112", name: "Changata", group: "thyolo" },
  { code: "310113", name: "Mbawela", group: "thyolo" },
  { code: "310114", name: "Nsabwe", group: "thyolo" },
  { code: "310115", name: "Thukuta", group: "thyolo" },
];
export const zomba_ruralCodes = [
  { code: "304101", name: "Nkapita", group: "zomba_rural" },
  { code: "304102", name: "Malemia", group: "zomba_rural" },
  { code: "304103", name: "Kuntumanji", group: "zomba_rural" },
  { code: "304104", name: "Mkumbira", group: "zomba_rural" },
  { code: "304105", name: "Nkagula", group: "zomba_rural" },
  { code: "304106", name: "Mlumbe", group: "zomba_rural" },
  { code: "304107", name: "Ntholowa", group: "zomba_rural" },
  { code: "304108", name: "Chikowi", group: "zomba_rural" },
  { code: "304109", name: "Mwambo", group: "zomba_rural" },
  { code: "304110", name: "Ngwelero", group: "zomba_rural" },
  { code: "304111", name: "Mbiza", group: "zomba_rural" },
  { code: "304112", name: "Zomba Mountain Reserve", group: "zomba_rural" },
];
export const zomba_urbanCodes = [
  { code: "305200", name: "Zomba CBD", group: "zomba_urban" },
  { code: "305201", name: "Ndola", group: "zomba_urban" },
  { code: "305202", name: "Zakazaka", group: "zomba_urban" },
  { code: "305203", name: "St Mary", group: "zomba_urban" },
  { code: "305204", name: "Nandolo", group: "zomba_urban" },
  { code: "305205", name: "Chirunga", group: "zomba_urban" },
  { code: "305206", name: "Masongola", group: "zomba_urban" },
  { code: "305207", name: "Mangasanja", group: "zomba_urban" },
  { code: "305208", name: "Mulunguzi", group: "zomba_urban" },
  { code: "305209", name: "Old Naisi", group: "zomba_urban" },
  { code: "305210", name: "Malonje", group: "zomba_urban" },
  { code: "305211", name: "Chinamwali", group: "zomba_urban" },
  { code: "305212", name: "Matawale", group: "zomba_urban" },
  { code: "305213", name: "Thom Allan", group: "zomba_urban" },
  { code: "305214", name: "Mpunga", group: "zomba_urban" },
  { code: "305215", name: "Sadzi", group: "zomba_urban" },
  { code: "305216", name: "Mponda Bwino", group: "zomba_urban" },
  { code: "305217", name: "Three Miles", group: "zomba_urban" },
  { code: "305218", name: "Mtiya", group: "zomba_urban" },
  { code: "305219", name: "Cobbe", group: "zomba_urban" },
];
